name: ADES107
on:
  workflow_dispatch:
    inputs:
      color:
        default: "red"

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: 8398a7/action-slack@v3
        with:
          custom_payload: '{ attachments: [{ color: process.env.INPUTS_COLOR }] }'
        env:
          INPUTS_COLOR: ${{ inputs.color }}
