name: ADES113
on: workflow_dispatch
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: azure/powershell@v2.0.0
        with:
          azPSVersion: latest
          inlineScript: Write-Output "Hello $env:INPUTS_NAME"
        env:
          INPUTS_NAME: ${{ inputs.name }}
