name: ADES101

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name to greet"

jobs:
  example_job:
    runs-on: ubuntu-latest
    env:
        INPUTS_NAME: ${{ inputs.name }}
    steps:
      - name: Example step
        uses: actions/github-script@v6

        with:
          script: |
            console.log(`Hello ${process.env.INPUTS_NAME}`)
