name: ADES108
on: 
  workflow_dispatch:
    inputs:
      color:
        description: "Colour"
        
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: appleboy/ssh-action@v1
        with:
          script: echo 'Hello $INPUTS_NAME'
        env:
          INPUTS_NAME: ${{ inputs.name }}


