name: ADES108
on:
  workflow_dispatch:
    inputs:
      name:
        default: "World"

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: appleboy/ssh-action@v1
        with:
          host: homepage
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: echo "Hello $INPUTS_NAME"
          envs: INPUTS_NAME
        env:
          INPUTS_NAME: ${{ inputs.name }}
