name: ADES100
on:
  workflow_dispatch:
    inputs:
      name:
        default: "World"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Apply env var fix
        run: |
          echo "Hello $INPUTS_NAME"
        env:
          INPUTS_NAME: ${{ inputs.name }}
