name: ADES108
on:
  workflow_dispatch:
    inputs:
      name:
        default: "World"

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Secret
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "Key is EMPTY"
          else
            echo "Key is SET"
          fi
      - name: Example step
        uses: appleboy/ssh-action@v1
        with:
          host: vm.cloud.cbh.kth.se
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 20213
          script: echo "Hello $INPUTS_NAME"
          envs: INPUTS_NAME
        env:
          INPUTS_NAME: ${{ inputs.name }}
