name: ADES104
on:
  workflow_dispatch:
    inputs:
      file: 
        description: "Path to the YAML file"
        required: true
        type: string
        
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq .app.version "$GITHUB_EVENT_INPUTS_FILE" -r
        env:
          GITHUB_EVENT_INPUTS_FILE: ${{ github.event.inputs.file }}
