name: ADES106
on:
  workflow_dispatch:
    inputs:
      value:
        default: "1"
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: cardinalby/js-eval-action@v1
        with:
          expression: 1 + parseInt(env.INPUTS_VALUE)
        env:
          INPUTS_VALUE: ${{ inputs.value }}
