name: ADES110
on: workflow_dispatch
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: Amadevus/pwsh-script@v2
        with:
          script: Write-Output "Hello $env:INPUTS_NAME"
        env:
          INPUTS_NAME: ${{ inputs.name }}
