name: Multiproblem
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name to greet"

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: roots/issue-closer-action@v1.2
        with:
          issue-close-message: Closing ${process.env.GITHUB_EVENT_ISSUE_TITLE}
          issue-pattern: ".*guidelines for Contributing.*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_EVENT_ISSUE_TITLE: ${{ github.event.issue.title }}
      - name: ADES101
        uses: actions/github-script@v6
        with:
          script: console.log(`Hello ${process.env.INPUTS_NAME}`)
        env:
          INPUTS_NAME: ${{ inputs.name }}
